{% set name = "basal-and-bark" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/basal_and_bark-{{ version }}.tar.gz
  sha256: b08995ba3d153d24f3f590ceb8d1723d14150bd2b6950ff143f51680317be67e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - folium
    - ipyleaflet
    - geopandas

test:
  imports:
    - basal_and_bark
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ZachDorm/basal_and_bark
  summary: Welcome to Basal and Bark, a spatial python package for working with forest data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ZachDorm
